Repository selsa-inube/design-system, pull requests merged in 2023-06, with the labels that each got.

#131 Develop the `<Nav />` component
  src/components/navigation/Nav/index.jsx
  src/components/navigation/Nav/stories/Nav.Default.stories.jsx
  src/components/navigation/Nav/stories/Nav.WithoutSections.stories.jsx
  src/components/navigation/Nav/stories/props.js
  src/components/navigation/Nav/styles.js
  src/components/navigation/NavLink/index.jsx
  src/components/navigation/NavLink/stories/NavLink.Default.stories.jsx
  src/components/navigation/NavLink/styles.js
  src/index.js
Labels: minor

#156 Fix the error for implemenation of `validateBoxModelMeasure`
  src/components/data/Text/index.jsx
  src/components/layouts/Stack/index.jsx
  src/utilities/transformedMeasure.js
Labels: patch

#157 Add 'button' type and prevent redirection in `<Button />`
  src/components/inputs/Button/index.jsx
  src/components/inputs/Button/stories/Button.Appearances.stories.jsx
  src/components/inputs/Button/stories/Button.Disabled.stories.jsx
  src/components/inputs/Button/stories/Button.FullWidth.stories.jsx
  src/components/inputs/Button/stories/Button.Icons.stories.jsx
  src/components/inputs/Button/stories/Button.Loading.stories.jsx
  src/components/inputs/Button/stories/Button.Spacing.stories.jsx
  src/components/inputs/Button/stories/Button.Variants.stories.jsx
  src/components/inputs/Button/stories/props.js
Labels: patch

#155 Adjust the `<Switch/>` to eliminate unnecessary space between elements when a label is not present
  src/components/inputs/Switch/index.jsx
Labels: patch

#153 Search `<Label />` with htmlFor when no `<input />`
  src/components/navigation/BreadcrumbEllipsis/index.jsx
  src/components/navigation/BreadcrumbEllipsis/styles.js
  src/components/navigation/BreadcrumbLink/index.jsx
  src/components/navigation/BreadcrumbMenuLink/index.jsx
  src/components/navigation/Breadcrumbs/index.jsx
  src/components/navigation/Breadcrumbs/styles.js
  src/components/navigation/Tab/index.jsx
  src/components/navigation/Tab/styles.js
Labels: patch

#132 Develop the `<FullscreenNav />` component
  .storybook/preview-body.html
  src/components/navigation/FullscreenNav/index.jsx
  src/components/navigation/FullscreenNav/stories/FullscreenNav.Default.stories.jsx
  src/components/navigation/FullscreenNav/stories/FullscreenNav.WithoutSections.stories.jsx
  src/components/navigation/FullscreenNav/stories/props.js
  src/components/navigation/FullscreenNav/styles.js
  src/components/navigation/NavLink/styles.js
Labels: minor

#160 Adjust `font-size` attribute of `<Tab/>`
  src/components/navigation/Tab/index.jsx
Labels: minor

#129 Develop the `<Table />` component
  src/components/data/Table/Pagination/index.jsx
  src/components/data/Table/Pagination/styles.js
  src/components/data/Table/index.jsx
  src/components/data/Table/interface.jsx
  src/components/data/Table/stories/Pagination.Default.stories.jsx
  src/components/data/Table/stories/PaginationController.jsx
  src/components/data/Table/stories/Table.Default.stories.jsx
  src/components/data/Table/stories/Table.Paginations.stories.jsx
  src/components/data/Table/stories/mucks.jsx
  src/components/data/Table/stories/props.js
  src/components/data/Table/stories/styles.js
  src/components/data/Table/styles.js
  src/index.js
Labels: minor

#162 Release version 4.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#166 Adjust the `<Button/>` to ensure that, when the isDisabled property is enabled, the button won't allow click interactions
  src/components/inputs/Button/index.jsx
Labels: bug

#170 Adjust the `<FullscreenNav/>` to include a scroll function for when the screen becomes too small
  src/components/navigation/FullscreenNav/styles.js
Labels: bug

#177 enable the export of the `<CountdownBar />` component to be used
  src/index.js
Labels: bug

#176 Adjust the `<CountDownBar/>` to pause when the user's cursor hovers over it
  src/components/feedback/CountdownBar/index.jsx
  src/components/feedback/CountdownBar/stories/ProgressBar.Default.stories.jsx
  src/components/feedback/CountdownBar/stories/props.js
  src/components/feedback/CountdownBar/styles.js
Labels: bug

#171 Create `<Header/>` component
  src/components/navigation/Header/index.jsx
  src/components/navigation/Header/stories/Header.Default.stories.jsx
  src/components/navigation/Header/stories/logo.jsx
  src/components/navigation/Header/stories/props.js
  src/components/navigation/Header/styles.js
  src/index.js
Labels: minor

#178 the 'title' attribute from the PropTypes of the `<Nav/>` component, as it is no longer requisite within that context
  src/components/navigation/Nav/index.jsx
Labels: bug

#179 Adjust the `<Blanket/>` to prevent content overflow when it is too large
  src/components/utils/Blanket/styles.js
Labels: bug

#181 Release new version 4.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#185 Adjust the <Table/>. Currently, it is throwing an error when we try to implement the actions
  src/components/data/Table/index.jsx
  src/components/data/Table/interface.jsx
  src/components/data/Table/stories/Table.Default.stories.jsx
  src/components/data/Table/stories/Table.Paginations.stories.jsx
  src/components/data/Table/stories/mucks.jsx
  src/components/data/Table/stories/props.js
Labels: bug

#184 Adjust `<CountDownBar/>` in order to manage the isPause property with other aproach
  src/components/feedback/CountdownBar/stories/CountdownBar.Default.stories.jsx
  src/components/feedback/CountdownBar/styles.js
Labels: bug

#190 Adjust `<Header/>` component to eliminate any embedded static code
  src/components/navigation/Header/index.jsx
  src/components/navigation/Header/stories/Header.Default.stories.jsx
  src/components/navigation/Header/stories/props.js
Labels: bug

#194 design-system new release 4.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#192 Adjust `<Header/>` in order to include props that manage the BusinessUnit
  src/components/data/User/index.jsx
  src/components/navigation/Header/index.jsx
  src/components/navigation/Header/stories/Header.Default.stories.jsx
  src/components/navigation/Header/stories/props.js
Labels: bug

#195 Adjust internal margin of the `<Nav/>` component to accurately conform to the provided design mockups
  src/components/navigation/Nav/index.jsx
Labels: bug

#196 Adjust `<Table/>` component such that it incorporates the modal in responsive mode and the 'open' attribute is set to true
  src/components/data/Table/DisplayEntry/index.jsx
  src/components/data/Table/index.jsx
  src/components/data/Table/interface.jsx
  src/components/data/Table/stories/Table.Default.stories.jsx
  src/components/data/Table/stories/Table.Paginations.stories.jsx
  src/components/data/Table/stories/props.js
  src/components/feedback/InteractiveModal/index.jsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.Default.stories.jsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.WithActions.stories.jsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.WithLabels.stories.jsx
  src/components/feedback/InteractiveModal/stories/props.js
  src/components/feedback/InteractiveModal/styles.js
Labels: minor

#200 Add margin and padding props to `<Switch/>`
  src/components/inputs/Switch/index.jsx
  src/components/inputs/Switch/stories/Switch.Checks.stories.jsx
  src/components/inputs/Switch/stories/Switch.Default.stories.jsx
  src/components/inputs/Switch/stories/Switch.Disabled.stories.jsx
  src/components/inputs/Switch/stories/Switch.Sizes.stories.jsx
  src/components/inputs/Switch/stories/Switch.WithLabel.stories.jsx
  src/components/inputs/Switch/stories/props.js
  src/components/inputs/Switch/styles.js
Labels: minor

#198 Install TypeScript
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.node.json
  vite.config.js
Labels: major

#191 Develop the `<TextArea />` component
  .gitignore
  package-lock.json
  src/components/inputs/TextArea/index.jsx
  src/components/inputs/TextArea/interface.jsx
  src/components/inputs/TextArea/stories/TextArea.Default.stories.jsx
  src/components/inputs/TextArea/stories/TextArea.controller.jsx
  src/components/inputs/TextArea/stories/props.js
  src/components/inputs/TextArea/styles.js
Labels: minor

#204 adjust settings to use styled-components and storybook with TS
  .storybook/main.js
  .storybook/main.ts
  .storybook/preview.ts
  src/vite-env.d.ts
Labels: minor

#208 Migrate useMediaQuery to TypeScript
  src/hooks/stories/Example.stories.tsx
  src/hooks/stories/IExampleSwitch.interface.ts
  src/hooks/useMediaQuery.js
  src/hooks/useMediaQuery.ts
Labels: minor

#210 Migrate `useMediaQueries` to TypeScript
  src/hooks/interfaces/MediaQueryListEvent.interface.ts
  src/hooks/interfaces/MediaQueryObject.interface.ts
  src/hooks/stories/ExampleMediaQueries.interface.ts
  src/hooks/stories/ExampleMediaQueries.stories.tsx
  src/hooks/types/MediaQueryList.type.ts
  src/hooks/useMediaQueries.js
  src/hooks/useMediaQueries.ts
  src/hooks/validators.ts
Labels: minor

#211 adjust the texts of actions and margins in `<InteractiveModal />`
  src/components/feedback/InteractiveModal/index.jsx
  src/components/feedback/InteractiveModal/styles.js
Labels: bug

#212 Migrate `<Blanket />` to TypeScript
  src/components/utils/Blanket/index.jsx
  src/components/utils/Blanket/index.tsx
  src/components/utils/Blanket/interfaces/interface.Blanket.ts
  src/components/utils/Blanket/stories/Blanket.stories.tsx
  src/components/utils/Blanket/styles.ts
Labels: minor

#209 migrate the `<Label />` component and its dependencies to `TypeScript`
  src/components/inputs/Label/index.tsx
  src/components/inputs/Label/interfaces/Label.interface.ts
  src/components/inputs/Label/stories/Label.Default.stories.tsx
  src/components/inputs/Label/stories/Label.IsFocused.stories.tsx
  src/components/inputs/Label/stories/Label.Size.stories.tsx
  src/components/inputs/Label/stories/Label.State.stories.tsx
  src/components/inputs/Label/stories/Label.isDisabled.stories.tsx
  src/components/inputs/Label/stories/props.ts
  src/components/inputs/Label/styles.ts
  src/components/inputs/Label/types/Label.type.ts
  tsconfig.json
Labels: minor

#203 Migrate component `<Avatar />` to `TypeScript`
  src/components/data/Avatar/index.tsx
  src/components/data/Avatar/interfaces/Avatar.interface.ts
  src/components/data/Avatar/stories/Avatar.Default.stories.tsx
  src/components/data/Avatar/stories/props.ts
  src/components/data/Avatar/styles.ts
Labels: minor
