Repository selsa-inube/design-system, pull requests merged in 2023-07, with the labels that each got.

#213 Migrate `<Tab />` to TypeScript
  src/components/navigation/Tab/index.tsx
  src/components/navigation/Tab/interfaces/Tab.interface.ts
  src/components/navigation/Tab/stories/Tab.Default.stories.tsx
  src/components/navigation/Tab/stories/TabController.tsx
  src/components/navigation/Tab/stories/props.ts
  src/components/navigation/Tab/styles.ts
Labels: minor

#217 Migrate component `<Spinner/>` to TypeScript
  src/components/feedback/Spinner/index.tsx
  src/components/feedback/Spinner/interfaces/Spinner.interface.ts
  src/components/feedback/Spinner/stories/Spinner.All.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Colors.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Default.stories.jsx
  src/components/feedback/Spinner/stories/Spinner.Default.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Sizes.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Transparency.stories.tsx
  src/components/feedback/Spinner/stories/props.ts
  src/components/feedback/Spinner/stories/styles.ts
  src/components/feedback/Spinner/styles.ts
  src/components/feedback/Spinner/types/Spinner.Appearance.type.ts
  src/components/feedback/Spinner/types/Spinner.Size.type.ts
Labels: minor

#219 Migrate `<Stack />` to `TypeScript`
  src/components/layouts/Stack/index.tsx
  src/components/layouts/Stack/interfaces/Stack.interface.ts
  src/components/layouts/Stack/stories/Stack.Default.stories.jsx
  src/components/layouts/Stack/stories/Stack.Default.stories.tsx
  src/components/layouts/Stack/stories/props.ts
  src/components/layouts/Stack/stories/stories.styles.ts
  src/components/layouts/Stack/styles.js
  src/components/layouts/Stack/styles.ts
  src/components/layouts/Stack/types/Stack.AlignItems.type.ts
  src/components/layouts/Stack/types/Stack.DirectionAlignments.ts
  src/components/layouts/Stack/types/Stack.FlexAlignments.ts
  src/components/layouts/Stack/types/Stack.WrapControl.type.ts
Labels: minor

#215 Migrate `<Text />` to TypeScript
  src/components/data/Text/index.tsx
  src/components/data/Text/interfaces/Text.interface.ts
  src/components/data/Text/stories/Text.Paragraphs.stories.tsx
  src/components/data/Text/stories/Text.Titles.stories.tsx
  src/components/data/Text/stories/props.ts
  src/components/data/Text/stories/styles.ts
  src/components/data/Text/styles.js
  src/components/data/Text/styles.ts
  src/components/data/Text/types/Text.AlignOptions.type.ts
  src/components/data/Text/types/Text.AppearancesOptions.type.ts
  src/components/data/Text/types/Text.HtmlElements.type.ts
  src/components/data/Text/types/Text.TyposOptions.type.ts
Labels: minor

#218 Migrate `<SkeletonIcon />` to TypeScript
  src/components/feedback/SkeletonIcon/index.tsx
  src/components/feedback/SkeletonIcon/interfaces/SkeletonIcon.interface.ts
  src/components/feedback/SkeletonIcon/stories/SkeletonIcon.Default.stories.tsx
  src/components/feedback/SkeletonIcon/stories/props.ts
  src/components/feedback/SkeletonIcon/styles.ts
Labels: minor

#222 Migrate `<User />` to TypeScript
  src/components/data/User/index.tsx
  src/components/data/User/interfaces/User.interface.ts
  src/components/data/User/stories/User.Default.stories.tsx
  src/components/data/User/stories/props.ts
  src/components/data/User/types/User.Size.type.ts
  src/components/layouts/Stack/interfaces/Stack.interface.ts
  src/components/layouts/Stack/stories/Stack.Default.stories.tsx
Labels: minor

#214 Migrate `<CountdownBar />` to TypeScript
  src/components/feedback/CountdownBar/index.tsx
  src/components/feedback/CountdownBar/interfaces/CountdownBar.interface.ts
  src/components/feedback/CountdownBar/stories/CountdownBar.Default.stories.tsx
  src/components/feedback/CountdownBar/stories/props.ts
  src/components/feedback/CountdownBar/styles.js
  src/components/feedback/CountdownBar/styles.ts
  src/components/feedback/CountdownBar/types/CountdownBar.Appearance.type.ts
Labels: minor

#220 Migrate <SkeletonLine /> to TypeScript
  src/components/feedback/SkeletonLine/index.tsx
  src/components/feedback/SkeletonLine/interfaces/SkeletonLine.interface.ts
  src/components/feedback/SkeletonLine/stories/SkeletonLine.Default.stories.tsx
  src/components/feedback/SkeletonLine/stories/props.ts
  src/components/feedback/SkeletonLine/styles.ts
Labels: minor

#224 Release design-system new version 5.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#221 Migrate `<BreadcrumbLink />` to TypeScript
  src/components/navigation/BreadcrumbLink/index.tsx
  src/components/navigation/BreadcrumbLink/interfaces/BreadcrumbLink.interface.ts
  src/components/navigation/BreadcrumbLink/stories/BreadcrumbLink.Default.stories.tsx
  src/components/navigation/BreadcrumbLink/stories/BreadcrumbLinkController.tsx
  src/components/navigation/BreadcrumbLink/stories/props.ts
  src/components/navigation/BreadcrumbLink/styles.ts
  src/components/navigation/BreadcrumbLink/types/BreadcrumbLink.typos.type.ts
Labels: minor

#216 Migrate `<BreadcrumbEllipsis />` to TypeScript
  src/components/navigation/BreadcrumbEllipsis/index.tsx
  src/components/navigation/BreadcrumbEllipsis/interfaces/BreadcrumbEllipsis.Route.interface.ts
  src/components/navigation/BreadcrumbEllipsis/interfaces/BreadcrumbEllipsis.interface.ts
  src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.tsx
  src/components/navigation/BreadcrumbEllipsis/stories/props.ts
  src/components/navigation/BreadcrumbEllipsis/styles.ts
  src/components/navigation/BreadcrumbEllipsis/types/BreadcrumbEllipsis.Typos.type.ts
  src/components/navigation/Breadcrumbs/index.jsx
Labels: minor

#225 Migrate `<BreadcrumbMenu />` to TypeScript
  src/components/navigation/BreadcrumbMenu/index.tsx
  src/components/navigation/BreadcrumbMenu/interfaces/BreadcrumbMenu.interface.ts
  src/components/navigation/BreadcrumbMenu/interfaces/BreadcrumbMenu.route.interface.ts
  src/components/navigation/BreadcrumbMenu/stories/BreadcrumbMenu.Default.stories.tsx
  src/components/navigation/BreadcrumbMenu/stories/props.ts
  src/components/navigation/BreadcrumbMenu/styles.ts
Labels: minor

#226 Migrate `<NavLink />` to `TypeScript`
  src/components/navigation/NavLink/index.tsx
  src/components/navigation/NavLink/interfaces/NavLink.interface.ts
  src/components/navigation/NavLink/stories/NavLink.Controller.tsx
  src/components/navigation/NavLink/stories/NavLink.Default.stories.tsx
  src/components/navigation/NavLink/stories/props.ts
  src/components/navigation/NavLink/styles.ts
Labels: minor

#227 Migrate `<Switch />` to TypeScript
  src/components/inputs/Label/interfaces/Label.interface.ts
  src/components/inputs/Label/styles.ts
  src/components/inputs/Switch/index.tsx
  src/components/inputs/Switch/interfaces/Switch.interface.ts
  src/components/inputs/Switch/stories/Switch.Checks.stories.tsx
  src/components/inputs/Switch/stories/Switch.Default.stories.tsx
  src/components/inputs/Switch/stories/Switch.Disabled.stories.jsx
  src/components/inputs/Switch/stories/Switch.Disabled.stories.tsx
  src/components/inputs/Switch/stories/Switch.Sizes.stories.tsx
  src/components/inputs/Switch/stories/Switch.WithLabel.stories.tsx
  src/components/inputs/Switch/stories/SwitchController.jsx
  src/components/inputs/Switch/stories/SwitchController.tsx
  src/components/inputs/Switch/stories/props.ts
  src/components/inputs/Switch/stories/stories.styles.ts
  src/components/inputs/Switch/styles.ts
  src/components/inputs/Switch/types/Switch.Size.type.ts
Labels: minor

#231 Migrate `<Button />` to TypeScript
  src/components/inputs/Button/index.tsx
  src/components/inputs/Button/interfaces/Button.interface.ts
  src/components/inputs/Button/stories/Button.Appearances.stories.tsx
  src/components/inputs/Button/stories/Button.Default.stories.tsx
  src/components/inputs/Button/stories/Button.Disabled.stories.tsx
  src/components/inputs/Button/stories/Button.FullWidth.stories.tsx
  src/components/inputs/Button/stories/Button.Icons.stories.tsx
  src/components/inputs/Button/stories/Button.Loading.stories.tsx
  src/components/inputs/Button/stories/Button.Spacing.stories.tsx
  src/components/inputs/Button/stories/Button.Variants.stories.tsx
  src/components/inputs/Button/stories/props.ts
  src/components/inputs/Button/stories/stories.styles.ts
  src/components/inputs/Button/styles.ts
  src/components/inputs/Button/types/Button.Appearances.type.ts
  src/components/inputs/Button/types/Button.Spacings.type.ts
  src/components/inputs/Button/types/Button.SpinnerColor.type.ts
  src/components/inputs/Button/types/Button.SpinnerColorHomologation.type.ts
  src/components/inputs/Button/types/Button.Types.type.ts
  src/components/inputs/Button/types/Button.Variants.type.ts
Labels: minor

#232 Migrate `<TextField />` to TypeScript
  src/components/inputs/Label/interfaces/Label.interface.ts
  src/components/inputs/TextField/index.tsx
  src/components/inputs/TextField/interface.tsx
  src/components/inputs/TextField/interfaces/TextField.Message.interface.ts
  src/components/inputs/TextField/interfaces/TextField.interface.ts
  src/components/inputs/TextField/stories/TextField.Default.stories.tsx
  src/components/inputs/TextField/stories/TextField.Disabled.stories.tsx
  src/components/inputs/TextField/stories/TextField.Invalid.stories.tsx
  src/components/inputs/TextField/stories/TextField.Number.stories.tsx
  src/components/inputs/TextField/stories/TextField.Required.stories.jsx
  src/components/inputs/TextField/stories/TextField.Required.stories.tsx
  src/components/inputs/TextField/stories/TextField.Search.stories.jsx
  src/components/inputs/TextField/stories/TextField.Search.stories.tsx
  src/components/inputs/TextField/stories/TextField.Sizes.stories.tsx
  src/components/inputs/TextField/stories/TextField.Valid.stories.tsx
  src/components/inputs/TextField/stories/TextfieldController.tsx
  src/components/inputs/TextField/stories/props.ts
  src/components/inputs/TextField/styles.ts
  src/components/inputs/TextField/types/TextField.InputType.type.ts
  src/components/inputs/TextField/types/TextField.Size.type.ts
  src/components/inputs/TextField/types/TextField.State.type.ts
Labels: minor

#230 Migrate `<Breadcrumbs />` to TypeScript
  src/components/navigation/Breadcrumbs/index.tsx
  src/components/navigation/Breadcrumbs/interfaces/Breadcrumbs.Item.interface.ts
  src/components/navigation/Breadcrumbs/interfaces/Breadcrumbs.interface.ts
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.Default.stories.tsx
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.Desktop.stories.tsx
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.Mobile.stories.tsx
  src/components/navigation/Breadcrumbs/stories/props.ts
  src/components/navigation/Breadcrumbs/styles.ts
  src/components/navigation/Breadcrumbs/types/Breadcrumb.Size.type.ts
Labels: minor

#239 Adjust `<Select/>` in order to add the exportation from the library
  src/index.ts
Labels: bug

#238 Update `<TextArea/>` to Incorporate Library Export Functionality
  src/index.ts
Labels: bug

#228 Migrate `<Tabs />` to TypeScript
  src/components/navigation/Tabs/index.tsx
  src/components/navigation/Tabs/interfaces/Tabs.Item.interface.ts
  src/components/navigation/Tabs/interfaces/Tabs.interface.ts
  src/components/navigation/Tabs/stories/Tabs.Default.stories.tsx
  src/components/navigation/Tabs/stories/Tabs.Responsive.stories.tsx
  src/components/navigation/Tabs/stories/TabsController.tsx
  src/components/navigation/Tabs/stories/TabsResponsiveController.tsx
  src/components/navigation/Tabs/stories/props.ts
  src/components/navigation/Tabs/styles.ts
  src/components/navigation/Tabs/types/Tabs.type.ts
Labels: minor

#240 Adjust `<Tabs/>` in order to review several issues
  src/components/inputs/DropDownMenu/index.jsx
  src/components/inputs/Select/interface.jsx
  src/components/navigation/Tabs/stories/Tabs.Default.stories.tsx
  src/components/navigation/Tabs/styles.ts
Labels: bug

#243 Adjust `<Button/>` in order to include isDisabled behavior to the type "link"
  src/components/inputs/Button/index.tsx
  src/components/inputs/Button/styles.ts
Labels: bug

#244 Adjust `<Blanket/>` to eliminate undesirable characteristics
  src/components/feedback/InteractiveModal/styles.js
  src/components/utils/Blanket/index.tsx
  src/components/utils/Blanket/styles.ts
  src/hooks/stories/Example.stories.tsx
Labels: bug

#247 Update src/index.tsx in order to include the exportation of `<InteractiveModal/>`
  src/index.ts
Labels: bug

#234 Migrate `<Table />` to TypeScript
  src/components/data/Table/DisplayEntry/index.tsx
  src/components/data/Table/Pagination/index.tsx
  src/components/data/Table/Pagination/styles.ts
  src/components/data/Table/index.tsx
  src/components/data/Table/interface.tsx
  src/components/data/Table/interfaces/Table.Action.interface.ts
  src/components/data/Table/interfaces/Table.Breakpoint.interface.ts
  src/components/data/Table/interfaces/Table.DisplayEntry.interface.ts
  src/components/data/Table/interfaces/Table.Entry.interface.ts
  src/components/data/Table/interfaces/Table.Pagination.interface.ts
  src/components/data/Table/interfaces/Table.Title.interface.ts
  src/components/data/Table/interfaces/Table.UI.interface.ts
  src/components/data/Table/interfaces/Table.interface.ts
  src/components/data/Table/stories/Pagination.Default.stories.tsx
  src/components/data/Table/stories/PaginationController.tsx
  src/components/data/Table/stories/Table.Default.stories.tsx
  src/components/data/Table/stories/Table.Paginations.stories.tsx
  src/components/data/Table/stories/mucks.tsx
  src/components/data/Table/stories/props.ts
  src/components/data/Table/stories/styles.ts
  src/components/data/Table/styles.ts
Labels: minor

#248 Adjust `<Button/>` in order to fix the type link because that's includes a wrong spacing
  src/components/inputs/Button/interfaces/Button.ActionStyle.interface.ts
  src/components/inputs/Button/interfaces/Button.Actions.interface.ts
  src/components/inputs/Button/interfaces/Button.BackgroundColorVariant.interface.ts
  src/components/inputs/Button/interfaces/Button.BorderColorVariant.interface.ts
  src/components/inputs/Button/interfaces/Button.BorderColors.interface.ts
  src/components/inputs/Button/interfaces/Button.ColorPalette.interface.ts
  src/components/inputs/Button/interfaces/Button.Cursors.interface.ts
  src/components/inputs/Button/interfaces/Button.HoverColors.interface.ts
  src/components/inputs/Button/interfaces/Button.Spacing.interface.ts
  src/components/inputs/Button/interfaces/Button.SpacingDetail.interface.ts
  src/components/inputs/Button/interfaces/Button.TextColors.interface.ts
  src/components/inputs/Button/interfaces/Button.VariantStyle.interface.ts
  src/components/inputs/Button/interfaces/Button.interface.ts
  src/components/inputs/Button/interfaces/button.BackgroundColors.interface.ts
  src/components/inputs/Button/styles.ts
Labels: bug

#249 Release design-system new version 5.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#245 Migrate `<Nav />` to TypeScript
  src/components/navigation/Nav/index.tsx
  src/components/navigation/Nav/interfaces/Nav.Link.interface.ts
  src/components/navigation/Nav/interfaces/Nav.LinkComponet.interface.ts
  src/components/navigation/Nav/interfaces/Nav.MultiSections.interface.ts
  src/components/navigation/Nav/interfaces/Nav.Navigation.interface.ts
  src/components/navigation/Nav/interfaces/Nav.OneSection.interface.ts
  src/components/navigation/Nav/interfaces/Nav.Sections.interface.ts
  src/components/navigation/Nav/interfaces/Nav.interface.ts
  src/components/navigation/Nav/stories/Nav.Default.stories.tsx
  src/components/navigation/Nav/stories/Nav.WithoutSections.stories.tsx
  src/components/navigation/Nav/stories/props.ts
  src/components/navigation/Nav/styles.ts
  src/components/navigation/NavLink/interfaces/NavLink.interface.ts
Labels: minor

#253 Ajust `<Nav /> in compile time
  src/components/navigation/FullscreenNav/interfaces/FullscreenNav.Link.interface.ts
  src/components/navigation/FullscreenNav/stories/FullscreenNav.Default.stories.tsx
  src/components/navigation/FullscreenNav/stories/FullscreenNav.WithoutSections.stories.tsx
  src/components/navigation/Nav/index.tsx
  src/components/navigation/Nav/interfaces/Nav.Link.interface.ts
  src/components/navigation/NavLink/interfaces/NavLink.interface.ts
Labels: bug

#254 Adjust `<Tabs/>` in order to set the output 'handleSelectedTab'
  src/components/navigation/Tabs/index.tsx
Labels: bug

#255 Release new version 5.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#256 Adjust `<Blanket/>` in order to add a height property for blanket-children's vertical aligment
  src/components/utils/Blanket/styles.ts
Labels: bug

#257 Release new version 5.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#258 Migrate `<Select />` to TypeScript
  src/components/inputs/Button/interfaces/Button.interface.ts
  src/components/inputs/DropDownMenu/index.jsx
  src/components/inputs/Select/index.tsx
  src/components/inputs/Select/interface.tsx
  src/components/inputs/Select/interfaces/Select.Options.interface.ts
  src/components/inputs/Select/interfaces/Select.Success.interface.ts
  src/components/inputs/Select/interfaces/Select.interface.ts
  src/components/inputs/Select/interfaces/SelectInterface.interface.ts
  src/components/inputs/Select/stories/Select.Default.stories.tsx
  src/components/inputs/Select/stories/Select.form.Controller.tsx
  src/components/inputs/Select/stories/Select.inForm.stories.tsx
  src/components/inputs/Select/stories/SelectController.tsx
  src/components/inputs/Select/stories/props.ts
  src/components/inputs/Select/stories/styles.ts
  src/components/inputs/Select/styles.ts
  src/components/inputs/Select/types/Select.Size.type.ts
  src/components/inputs/Select/types/Select.States.type.ts
  src/index.ts
Labels: minor

#252 Create and export new inube color tokens
  src/shared/tokens/color/blocks/stroke.ts
  src/shared/tokens/color/blocks/surface.ts
  src/shared/tokens/color/blocks/text.ts
  src/shared/tokens/color/color.ts
  src/shared/tokens/color/palette/palette.ts
  src/shared/tokens/index.ts
Labels: important

#259 Create and export new inube spacing tokens
  package-lock.json
  src/index.ts
  src/shared/tokens/color/blocks/stroke.ts
  src/shared/tokens/color/blocks/surface.ts
  src/shared/tokens/color/blocks/text.ts
  src/shared/tokens/color/color.ts
  src/shared/tokens/color/palette/palette.ts
  src/shared/tokens/index.ts
  src/shared/tokens/spacing/spacing.ts
Labels: minor

#261 Adjust height property inside of `<Blanket/>`
  package-lock.json
  src/components/utils/Blanket/styles.ts
Labels: bug

#262 Release design-system new version 5.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#260 Add autodocs to all Storybook stories
  .storybook/main.ts
  package-lock.json
  src/components/feedback/InteractiveModal/stories/InteractiveModal.Default.stories.jsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.WithActions.stories.jsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.WithLabels.stories.jsx
  src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.tsx
  src/components/navigation/BreadcrumbMenu/stories/BreadcrumbMenu.Default.stories.tsx
  src/components/utils/Blanket/stories/Blanket.stories.tsx
  src/components/utils/Blanket/stories/styles.ts
Labels: documentation

#264 Create and export new inube `typography` tokens
  src/shared/tokens/index.ts
  src/shared/tokens/typography/blocks/Body.ts
  src/shared/tokens/typography/blocks/Display.ts
  src/shared/tokens/typography/blocks/Headline.ts
  src/shared/tokens/typography/blocks/Label.ts
  src/shared/tokens/typography/blocks/Title.ts
  src/shared/tokens/typography/typography.ts
Labels: minor

#263 Adjust `<DropdowItem/>` in order to make it more accuracy to the design
  src/components/inputs/DropDownItem/stories/DropDownItem.Default.stories.jsx
  src/components/inputs/DropDownItem/styles.js
Labels: bug

#266 Identify & adjust the stories in order to complete the documentation for the whole design-system
  src/components/data/Avatar/stories/Avatar.Default.stories.tsx
  src/components/data/Avatar/stories/props.ts
  src/components/data/Table/stories/Pagination.Default.stories.tsx
  src/components/data/Table/stories/props.ts
  src/components/data/User/stories/User.Default.stories.tsx
  src/components/data/User/stories/props.ts
  src/components/feedback/CountdownBar/stories/CountdownBar.Default.stories.tsx
  src/components/feedback/CountdownBar/stories/props.ts
  src/components/feedback/SkeletonIcon/stories/SkeletonIcon.Default.stories.tsx
  src/components/feedback/SkeletonIcon/stories/props.ts
  src/components/feedback/Spinner/stories/Spinner.All.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Colors.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Default.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Sizes.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Transparency.stories.tsx
  src/components/feedback/Spinner/stories/props.ts
  src/components/inputs/Button/stories/Button.Appearances.stories.tsx
  src/components/inputs/Button/stories/Button.Default.stories.tsx
  src/components/inputs/Button/stories/Button.Disabled.stories.tsx
  src/components/inputs/Button/stories/Button.FullWidth.stories.tsx
  src/components/inputs/Button/stories/Button.Icons.stories.tsx
  src/components/inputs/Button/stories/Button.Loading.stories.tsx
  src/components/inputs/Button/stories/Button.Spacing.stories.tsx
  src/components/inputs/Button/stories/Button.Variants.stories.tsx
  src/components/inputs/Button/stories/props.ts
  src/components/inputs/DropDownItem/stories/DropDownItem.Default.stories.jsx
  src/components/inputs/DropDownItem/stories/props.js
  src/components/inputs/DropDownMenu/stories/DropDownMenu.Default.stories.jsx
  src/components/inputs/DropDownMenu/stories/props.js
  src/components/inputs/Select/stories/props.ts
  src/components/inputs/Switch/stories/Switch.Checks.stories.tsx
  src/components/inputs/Switch/stories/Switch.Default.stories.tsx
  src/components/inputs/Switch/stories/props.ts
  src/components/inputs/TextArea/stories/props.js
  src/components/inputs/TextField/stories/props.ts
  src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.tsx
  src/components/navigation/BreadcrumbEllipsis/stories/props.ts
  src/components/navigation/BreadcrumbLink/stories/BreadcrumbLink.Default.stories.tsx
  src/components/navigation/BreadcrumbLink/stories/props.ts
  src/components/navigation/BreadcrumbMenu/stories/BreadcrumbMenu.Default.stories.tsx
  src/components/navigation/BreadcrumbMenu/stories/props.ts
  src/components/navigation/BreadcrumbMenuLink/stories/BreadcrumbMenuLink.Default.stories.tsx
  src/components/navigation/BreadcrumbMenuLink/stories/props.ts
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.Default.stories.tsx
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.Desktop.stories.tsx
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.Mobile.stories.tsx
  src/components/navigation/Breadcrumbs/stories/props.ts
  src/components/navigation/FullscreenNav/stories/props.ts
  src/components/navigation/Header/stories/props.js
  src/components/navigation/Nav/index.tsx
  src/components/navigation/Nav/stories/Nav.Default.stories.tsx
  src/components/navigation/Nav/stories/Nav.WithoutSections.stories.tsx
  src/components/navigation/Nav/stories/props.ts
  src/components/navigation/NavLink/stories/NavLink.Default.stories.tsx
  src/components/navigation/NavLink/stories/props.ts
  src/components/navigation/Tabs/stories/Tabs.Default.stories.tsx
  src/components/navigation/Tabs/stories/props.ts
Labels: bug

#268 Create the `<Icon />` component
  src/components/inputs/Icon/index.tsx
  src/components/inputs/Icon/interfaces/Icon.interface.ts
  src/components/inputs/Icon/stories/Icon.Default.stories.tsx
  src/components/inputs/Icon/stories/props.ts
  src/components/inputs/Icon/styles.ts
  src/components/inputs/Icon/types/Icon.Appearance.type.ts
  src/components/inputs/Icon/types/Icon.Shape.type.ts
  src/components/inputs/Icon/types/Icon.Spacing.type.ts
  src/components/inputs/Icon/types/Icon.Variant.type.ts
Labels: minor

#273 Adjust `<Header/>` in order to make the box-shadow be more tick
  src/components/navigation/Header/styles.js
Labels: bug

#274 Adjust `<Nav/>` in order to allow to the logout has a dynamic text
  src/components/navigation/FullscreenNav/index.tsx
  src/components/navigation/FullscreenNav/interfaces/FullscreenNav.FullscreenMenu.interface.ts
  src/components/navigation/FullscreenNav/interfaces/FullscreenNav.interface.ts
  src/components/navigation/FullscreenNav/stories/FullscreenNav.Default.stories.tsx
  src/components/navigation/FullscreenNav/stories/FullscreenNav.WithoutSections.stories.tsx
  src/components/navigation/Nav/index.tsx
  src/components/navigation/Nav/interfaces/Nav.interface.ts
  src/components/navigation/Nav/stories/Nav.Default.stories.tsx
  src/components/navigation/Nav/stories/Nav.WithoutSections.stories.tsx
Labels: bug

#275 Release new version 5.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#276 Refactor `<Avatar />` using the `<Icon />` component
  src/components/data/Avatar/index.tsx
  src/components/data/Avatar/styles.ts
  src/components/feedback/Icon/index.tsx
  src/components/feedback/Icon/interfaces/Icon.interface.ts
  src/components/feedback/Icon/stories/Icon.Default.stories.tsx
  src/components/feedback/Icon/stories/props.ts
  src/components/feedback/Icon/styles.ts
  src/components/feedback/Icon/types/Icon.Appearance.type.ts
  src/components/feedback/Icon/types/Icon.Shape.type.ts
  src/components/feedback/Icon/types/Icon.Spacing.type.ts
  src/components/feedback/Icon/types/Icon.Variant.type.ts
  src/components/inputs/Icon/types/Icon.Appearance.type.ts
Labels: minor

#278 Move `<Icon />` to /data folder
  src/components/data/Avatar/index.tsx
  src/components/data/Icon/index.tsx
  src/components/data/Icon/interfaces/Icon.interface.ts
  src/components/data/Icon/stories/Icon.Default.stories.tsx
  src/components/data/Icon/stories/props.ts
  src/components/data/Icon/styles.ts
  src/components/data/Icon/types/Icon.Appearance.type.ts
  src/components/data/Icon/types/Icon.Shape.type.ts
  src/components/data/Icon/types/Icon.Spacing.type.ts
  src/components/data/Icon/types/Icon.Variant.type.ts
  src/index.ts
Labels: bug

#272 Refactor `<Text />` component with new tokens and props
  src/components/data/Table/Pagination/index.tsx
  src/components/data/Table/interface.tsx
  src/components/data/Text/index.tsx
  src/components/data/Text/interfaces/Text.interface.ts
  src/components/data/Text/stories/Text.Dafault.stories.tsx
  src/components/data/Text/stories/Text.Paragraphs.stories.tsx
  src/components/data/Text/stories/Text.Titles.stories.tsx
  src/components/data/Text/stories/props.ts
  src/components/data/Text/styles.ts
  src/components/data/Text/types/Text.AlignOptions.type.ts
  src/components/data/Text/types/Text.AppearancesOptions.type.ts
  src/components/data/Text/types/Text.Size.type.ts
  src/components/data/Text/types/Text.TyposOptions.type.ts
  src/components/data/User/index.tsx
  src/components/feedback/InteractiveModal/index.jsx
  src/components/inputs/Select/interface.tsx
  src/components/inputs/TextArea/interface.jsx
  src/components/inputs/TextField/interface.tsx
  src/components/navigation/BreadcrumbEllipsis/index.tsx
  src/components/navigation/BreadcrumbEllipsis/interfaces/BreadcrumbEllipsis.interface.ts
  src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.tsx
  src/components/navigation/BreadcrumbEllipsis/stories/props.ts
  src/components/navigation/BreadcrumbEllipsis/types/BreadcrumbEllipsis.Typos.type.ts
  src/components/navigation/BreadcrumbLink/index.tsx
  src/components/navigation/BreadcrumbLink/types/BreadcrumbLink.typos.type.ts
  src/components/navigation/BreadcrumbMenuLink/index.tsx
  src/components/navigation/BreadcrumbMenuLink/types/BreadcrumbMenuLink.typos.type.ts
  src/components/navigation/Breadcrumbs/index.tsx
  src/components/navigation/Breadcrumbs/types/Breadcrumb.Size.type.ts
  src/components/navigation/FullscreenNav/index.tsx
  src/components/navigation/Nav/index.tsx
  src/components/navigation/Tab/index.tsx
  src/hooks/stories/ExampleMediaQueries.stories.tsx
  src/shared/tokens/color/blocks/text.ts
  src/shared/tokens/typography/blocks/body.ts
  src/utilities/transformedMeasure.js
Labels: minor

#277 Refactor the `<Stack/>` component with new props
  src/components/layouts/Stack/index.tsx
  src/components/layouts/Stack/interfaces/Stack.interface.ts
  src/components/layouts/Stack/stories/Squares.tsx
  src/components/layouts/Stack/stories/Stack.Default.stories.tsx
  src/components/layouts/Stack/stories/props.ts
  src/components/layouts/Stack/stories/stories.styles.ts
  src/components/layouts/Stack/styles.ts
  src/components/layouts/Stack/types/Stack.AlignContent.type.ts
  src/components/layouts/Stack/types/Stack.AlignItems.type.ts
  src/components/layouts/Stack/types/Stack.DirectionAlignment.type.ts
  src/components/layouts/Stack/types/Stack.DirectionAlignments.ts
  src/components/layouts/Stack/types/Stack.FlexAlignments.ts
  src/components/layouts/Stack/types/Stack.JustifyContent.type.ts
  src/components/layouts/Stack/types/Stack.WrapControl.type.ts
  src/utilities/validateBoxModelMeasure.js
Labels: minor

#280 Release new version v5.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#284 Refactor `<Icon />` and change isDisabled prop for just disabled
  src/components/data/Icon/index.tsx
  src/components/data/Icon/interfaces/Icon.interface.ts
  src/components/data/Icon/stories/Icon.Default.stories.tsx
  src/components/data/Icon/stories/props.ts
  src/components/data/Icon/styles.ts
Labels: minor

#286 Release new version 5.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#282 Generalize the appearance interface definition
  src/shared/types/Appearance.type.ts
Labels: minor

#281 Refactor `<Icon />` to use "icon" prop instead of children
  src/components/data/Icon/index.tsx
  src/components/data/Icon/interfaces/Icon.interface.ts
  src/components/data/Icon/stories/Icon.Default.stories.tsx
  src/components/data/Icon/stories/props.ts
Labels: minor

#287 Pass default values in stories args
  src/components/data/Icon/index.tsx
  src/components/data/Icon/stories/Icon.Default.stories.tsx
  src/components/feedback/CountdownBar/stories/CountdownBar.Default.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.All.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Colors.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Default.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Sizes.stories.tsx
  src/components/feedback/Spinner/stories/Spinner.Transparency.stories.tsx
  src/components/inputs/Button/stories/Button.Default.stories.tsx
  src/components/inputs/Button/stories/Button.Disabled.stories.tsx
  src/components/inputs/Label/stories/Label.Default.stories.tsx
  src/components/inputs/Label/stories/Label.Size.stories.tsx
  src/components/inputs/Select/stories/Select.Default.stories.tsx
  src/components/inputs/Switch/stories/Switch.Checks.stories.tsx
  src/components/inputs/Switch/stories/Switch.Default.stories.tsx
  src/components/inputs/Switch/stories/Switch.Disabled.stories.tsx
  src/components/inputs/Switch/stories/Switch.Sizes.stories.tsx
  src/components/inputs/Switch/stories/Switch.WithLabel.stories.tsx
  src/components/inputs/TextArea/stories/TextArea.Default.stories.jsx
  src/components/inputs/TextField/stories/TextField.Disabled.stories.tsx
  src/components/inputs/TextField/stories/TextField.Required.stories.tsx
  src/components/inputs/TextField/stories/TextField.Search.stories.tsx
  src/components/inputs/TextField/stories/TextField.Sizes.stories.tsx
  src/components/inputs/TextField/stories/TextField.Valid.stories.tsx
  src/components/layouts/Stack/index.tsx
  src/components/layouts/Stack/stories/Stack.Default.stories.tsx
  src/components/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.Default.stories.tsx
  src/components/navigation/BreadcrumbLink/stories/BreadcrumbLink.Default.stories.tsx
  src/components/navigation/BreadcrumbMenuLink/stories/BreadcrumbMenuLink.Default.stories.tsx
Labels: minor

#289 Remove decorators of `<User />` stories
  src/components/data/User/stories/User.Default.stories.tsx
Labels: minor

#291 Remove decorators in `<Avatar />` stories
  src/components/data/Avatar/stories/Avatar.Default.stories.tsx
  src/components/data/Avatar/stories/props.ts
Labels: minor

#290 Refactor `<Icon />` to control appearance in props interface, not in styles
  src/components/data/Icon/interfaces/Icon.interface.ts
  src/components/data/Icon/styles.ts
  src/components/data/Icon/types/Icon.Appearance.type.ts
Labels: minor

#293 Refactor `<Icon />` stories
  src/components/data/Icon/stories/Icon.Default.stories.tsx
  src/components/data/Icon/stories/props.ts
Labels: minor

#296 Delete transformedSize from `<User />`
  src/components/data/User/index.tsx
Labels: minor

#297 Refactor `<User />` to use spacing tokens in Stack gaps
  src/components/data/User/index.tsx
Labels: minor

#295 Remove decorators from `<Icon />` stories
  src/components/data/Icon/stories/Icon.Default.stories.tsx
Labels: minor

#294 Create a Themed story for `<Icon />`
  src/components/data/Icon/stories/Icon.Default.stories.tsx
  src/shared/themes/presente/color/blocks/stroke.ts
  src/shared/themes/presente/color/blocks/surface.ts
  src/shared/themes/presente/color/blocks/text.ts
  src/shared/themes/presente/color/color.ts
  src/shared/themes/presente/color/palette/palette.ts
  src/shared/themes/presente/index.ts
Labels: minor

#292 Refactor `<User />` to change "businessUnit" prop for `client`
  src/components/data/Avatar/index.tsx
  src/components/data/Icon/styles.ts
  src/components/data/User/index.tsx
  src/components/data/User/interfaces/User.interface.ts
  src/components/data/User/stories/User.Default.stories.tsx
  src/components/data/User/stories/props.ts
  src/components/navigation/Header/index.jsx
Labels: minor

#298 Create Themed story of `<Avatar />`
  src/components/data/Avatar/stories/Avatar.Default.stories.tsx
  src/components/data/Avatar/stories/props.ts
Labels: minor
