Repository selsa-inube/design-system, pull requests merged in 2023-04, with the labels that each got.

#88 <Button /> should have a width to fit the content if isFullWidth is false
  src/components/inputs/Button/stories/Button.Default.stories.js
  src/components/inputs/Button/styles.js
Labels: patch

#93 Simplify the <Switch /> stories using <Stack />
  src/components/inputs/Switch/stories/Switch.Checks.stories.js
  src/components/inputs/Switch/stories/Switch.Disabled.stories.js
  src/components/inputs/Switch/stories/Switch.Sizes.stories.js
  src/components/inputs/Switch/stories/Switch.WithLabel.stories.js
  src/components/inputs/Switch/stories/stories.styles.js
Labels: minor

#55 Create <TextField />
  .gitignore
  src/components/inputs/Label/styles.js
  src/components/inputs/TextField/index.jsx
  src/components/inputs/TextField/interface.jsx
  src/components/inputs/TextField/stories/TextField.Default.stories.js
  src/components/inputs/TextField/stories/TextField.Disabled.stories.js
  src/components/inputs/TextField/stories/TextField.Invalid.stories.js
  src/components/inputs/TextField/stories/TextField.Number.stories.js
  src/components/inputs/TextField/stories/TextField.Required.stories.js
  src/components/inputs/TextField/stories/TextField.Search.stories.js
  src/components/inputs/TextField/stories/TextField.Sizes.stories.js
  src/components/inputs/TextField/stories/TextField.Valid.stories.js
  src/components/inputs/TextField/stories/TextfieldController.jsx
  src/components/inputs/TextField/stories/props.js
  src/components/inputs/TextField/styles.js
Labels: minor

#97 Verify the <User /> component for It has an improper gap between the avatar and the text
  src/components/data/User/index.jsx
  src/components/data/User/styles.js
Labels: patch

#89 Create <Tabs/>
  src/components/navigation/Tab/styles.js
  src/components/navigation/Tabs/index.jsx
  src/components/navigation/Tabs/stories/Tabs.Default.stories.js
  src/components/navigation/Tabs/stories/TabsController.jsx
  src/components/navigation/Tabs/stories/props.js
  src/components/navigation/Tabs/styles.js
  src/index.js
Labels: minor

#95 Create <Breadcrumbs/>
  src/components/navigation/BreadcrumbLink/index.jsx
  src/components/navigation/BreadcrumbLink/stories/BreadcrumbLink.Default.stories.js
  src/components/navigation/BreadcrumbLink/styles.js
  src/components/navigation/Breadcrumbs/index.jsx
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.Default.stories.js
  src/components/navigation/Breadcrumbs/stories/props.js
  src/components/navigation/Breadcrumbs/styles.js
  src/index.js
Labels: minor

#98 Sync Label and TextField so there is no state homologation
  src/components/inputs/Label/index.jsx
  src/components/inputs/Label/stories/Label.Default.stories.js
  src/components/inputs/Label/stories/Label.IsFocused.stories.js
  src/components/inputs/Label/stories/Label.Size.stories.js
  src/components/inputs/Label/stories/Label.State.stories.js
  src/components/inputs/Label/stories/Label.isDisabled.stories.js
  src/components/inputs/Label/stories/props.js
  src/components/inputs/Label/stories/stories.styles.js
  src/components/inputs/Label/styles.js
  src/components/inputs/TextField/index.jsx
  src/components/inputs/TextField/interface.jsx
  src/components/inputs/TextField/stories/TextField.Sizes.stories.js
Labels: major

#107 Remove pointer-events: none from `Blanket`
  src/components/utils/Blanket/styles.js
Labels: patch

#111 `<Tabs />` are starting without left-padding for first `<Tab />`
  src/components/navigation/Tabs/styles.js
Labels: patch

#100 Extend button to also be of type "link" so that it can enable navigation
  src/components/inputs/Button/index.jsx
  src/components/inputs/Button/stories/Button.Appearances.stories.js
  src/components/inputs/Button/stories/Button.Default.stories.js
  src/components/inputs/Button/stories/Button.Disabled.stories.js
  src/components/inputs/Button/stories/Button.FullWidth.stories.js
  src/components/inputs/Button/stories/Button.Icons.stories.js
  src/components/inputs/Button/stories/Button.Loading.stories.js
  src/components/inputs/Button/stories/Button.Spacing.stories.js
  src/components/inputs/Button/stories/Button.Variants.stories.js
  src/components/inputs/Button/stories/ButtonController.jsx
  src/components/inputs/Button/stories/props.js
  src/components/inputs/Button/styles.js
Labels: minor

#121 Adjust height of `<TextField />` for "wide" and "compact" sizes
  src/components/inputs/TextField/styles.js
Labels: patch

#120 When re-sizing the screen to test responsive, there is an error about a wrong prop type in `<User />`
  src/components/layouts/Stack/index.jsx
Labels: patch

#124 Adjust the use of typography tokens in `<Button />`
  src/components/inputs/Button/styles.js
Labels: patch
