Repository selsa-inube/design-system, pull requests merged in 2023-10, with the labels that each got.

#529 Make it a wrapper that just render children in `<OptionList />`
  src/components/inputs/Select/OptionItem/index.tsx
  src/components/inputs/Select/OptionList/OptionList.stories.tsx
  src/components/inputs/Select/OptionList/index.tsx
  src/components/inputs/Select/index.tsx
  src/components/inputs/Select/interface.tsx
  src/components/inputs/Select/stories/Select.form.Controller.tsx
  src/components/inputs/Select/stories/Select.inForm.stories.tsx
  src/components/inputs/Select/stories/SelectController.tsx
  src/components/navigation/Tabs/index.tsx
Labels: minor

#537 Delete `ISelectStateProps` interface in `<Select />`
  src/components/inputs/Select/interface.tsx
Labels: minor

#538 Refactor background to background-color in `<Select />`
  src/components/inputs/Select/styles.ts
Labels: minor

#541 split the `border` property into three (`border-width`, `border-style`, `border-color`) in `<Select />`
  src/components/inputs/Select/styles.ts
  src/components/navigation/Header/styles.ts
Labels: minor

#543 Use `<Stack/>` component in `<Message />` in `<Select />`
  src/components/inputs/Select/interface.tsx
  src/components/inputs/Select/styles.ts
Labels: minor

#542 `<Header />:` `StyledHeader` should be a `<header>` html element, not a div
  src/components/navigation/Header/styles.ts
Labels: minor

#549 `<Header />:` Remove `logoutPath` and `logoutTitle` props
  src/components/navigation/Header/index.tsx
  src/components/navigation/Header/props.ts
  src/components/navigation/Header/stories/Header.stories.tsx
Labels: minor

#544 `<Header />:` rename `logo` for `logoURL`
  src/components/navigation/Header/index.tsx
  src/components/navigation/Header/props.ts
  src/components/navigation/Header/stories/Header.stories.tsx
Labels: minor

#548 `<Header />:` rename `businessUnit` prop for `client`
  src/components/navigation/Header/index.tsx
  src/components/navigation/Header/props.ts
  src/components/navigation/Header/stories/Header.stories.tsx
Labels: minor

#547 `<Header />:` fix the Themed story
  src/components/navigation/Header/styles.ts
Labels: minor

#550 Refactor extension of `ISelectProps` in `<Select />`
  src/components/inputs/Select/index.tsx
  src/components/inputs/Select/interface.tsx
Labels: minor

#552 Options list `<OptionList />` should overlap other components
  src/components/inputs/Select/OptionList/styled.ts
Labels: minor

#554 Rename isDisabled prop to disabled in `<NavLink />`
  src/components/navigation/NavLink/index.tsx
  src/components/navigation/NavLink/props.ts
  src/components/navigation/NavLink/stories/NavLink.stories.tsx
  src/components/navigation/NavLink/styles.ts
Labels: minor

#556 Remove `handleBlur` prop in `<NavLink />`
  src/components/navigation/NavLink/index.tsx
  src/components/navigation/NavLink/props.ts
  src/components/navigation/NavLink/stories/NavLink.Controller.tsx
Labels: minor

#511 Create the `<Assisted />` component
  src/components/feedback/Assisted/index.tsx
  src/components/feedback/Assisted/props.ts
  src/components/feedback/Assisted/stories/Assisted.Controller.tsx
  src/components/feedback/Assisted/stories/Assisted.stories.tsx
  src/components/feedback/Assisted/styles.ts
  src/index.ts
Labels: minor

#555 Rename `isSelected` prop to `selected` in `NavLink />`
  src/components/navigation/Nav/index.tsx
  src/components/navigation/NavLink/index.tsx
  src/components/navigation/NavLink/props.ts
  src/components/navigation/NavLink/stories/NavLink.Controller.tsx
  src/components/navigation/NavLink/styles.ts
Labels: minor

#553 `<Header />:` remove `isBusinessUnit` prop
  src/components/navigation/Header/index.tsx
  src/components/navigation/Header/props.ts
  src/components/navigation/Header/stories/Header.stories.tsx
Labels: minor

#561 Delete `background-size` CSS property in `<NavLink />`
  src/components/navigation/NavLink/styles.ts
Labels: minor

#551 `<Header />:` Use stack and remove flex properties from `StyledHeader`
  src/components/navigation/Header/index.tsx
  src/components/navigation/Header/styles.ts
Labels: minor

#562 `<Tabs />:` rename `isDropDownOpen` state to `displayList`
  src/components/navigation/Tabs/index.tsx
Labels: minor

#563 `<Tabs />:` rename `onSelectTab` prop to `onChange`
  src/components/navigation/Tabs/index.tsx
  src/components/navigation/Tabs/props.ts
  src/components/navigation/Tabs/stories/TabsController.tsx
  src/components/navigation/Tabs/stories/TabsResponsiveController.tsx
Labels: minor

#557 `<Header />:` Decouple `LogoAndNav` component
  src/components/navigation/Header/index.tsx
Labels: minor

#564 `<Tabs />:` delete `Tabs.Responsive` story
  src/components/navigation/Tabs/stories/Tabs.Responsive.stories.tsx
  src/components/navigation/Tabs/stories/Tabs.stories.tsx
  src/components/navigation/Tabs/stories/TabsResponsiveController.tsx
Labels: minor

#560 use new color spacing tokens in `<NavLink />`
  src/components/navigation/NavLink/index.tsx
  src/components/navigation/NavLink/stories/NavLink.stories.tsx
  src/components/navigation/NavLink/styles.ts
Labels: minor

#558 Create the `<Grid />` component
  src/components/layouts/Grid/index.tsx
  src/components/layouts/Grid/props.ts
  src/components/layouts/Grid/stories/Grid.stories.tsx
  src/components/layouts/Grid/stories/stories.styles.ts
  src/components/layouts/Grid/styles.ts
  src/index.ts
Labels: minor

#567 `<Tabs />:` delete `selectedTabLabel` state
  src/components/navigation/Tabs/Tab/index.tsx
  src/components/navigation/Tabs/Tab/stories/TabController.tsx
  src/components/navigation/Tabs/index.tsx
  src/components/navigation/Tabs/stories/TabsController.tsx
  src/components/navigation/Tabs/styles.ts
Labels: minor

#569 `<Tab />:` rename title of stories so it is rendered in storybook inside of Tabs
  src/components/navigation/Tabs/Tab/stories/Tab.stories.tsx
Labels: minor

#568 `<Nav />:` refactor to use new color tokens
  src/components/navigation/Nav/styles.ts
Labels: minor

#570 use `<Grid />` component in `<NavLink>`.
  src/components/navigation/NavLink/index.tsx
  src/components/navigation/NavLink/styles.ts
Labels: minor

#573 `<BreadcrumbEllipsis />:` refactor to use new color tokens
  src/components/navigation/Breadcrumbs/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.stories.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbEllipsis/styles.ts
  src/components/navigation/Header/stories/Header.stories.tsx
Labels: minor

#571 Remove INavOneSectionProps & INavMultiSectionsProps in `<Nav />`
  src/components/navigation/Nav/index.tsx
Labels: minor

#578 `<BreadcrumbEllipsis />:` delete `defaultTypo` variable
  src/components/navigation/Breadcrumbs/BreadcrumbEllipsis/index.tsx
Labels: minor

#579 `<BreadcrumbEllipsis />:` delete `IRoute` interface
  src/components/navigation/Breadcrumbs/BreadcrumbEllipsis/index.tsx
Labels: minor

#580 `<BreadcrumbMenu />:` delete `IBreadcrumbRoute` interface
  src/components/navigation/Breadcrumbs/BreadcrumbMenu/index.tsx
Labels: minor

#577 Delete `defaultTypo` & `defaultIsActive` variables `<BreadcrumbLink />`
  src/components/navigation/Breadcrumbs/BreadcrumbLink/index.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbLink/props.ts
  src/components/navigation/Breadcrumbs/BreadcrumbLink/stories/BreadcrumbLink.stories.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbLink/stories/BreadcrumbLinkController.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbLink/styles.ts
  src/components/navigation/Breadcrumbs/index.tsx
Labels: minor

#581 `<BreadcrumbMenu />:` delete `IBreadcrumbMenuProps` interface
  src/components/navigation/Breadcrumbs/BreadcrumbEllipsis/index.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbMenu/index.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbMenu/stories/BreadcrumbMenu.stories.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbMenu/styles.ts
  src/components/navigation/Breadcrumbs/props.ts
Labels: minor

#575 `<Tabs />:` refactor `handleOptionClick` function
  src/components/navigation/Tabs/index.tsx
  src/components/navigation/Tabs/stories/TabsController.tsx
Labels: minor

#582 `<BreadcrumbMenuLink />:` delete `IBreadcrumbMenuLinkProps`
  src/components/navigation/Breadcrumbs/BreadcrumbLink/index.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbLink/props.ts
  src/components/navigation/Breadcrumbs/BreadcrumbLink/stories/BreadcrumbLink.stories.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbMenu/index.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbMenuLink/index.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbMenuLink/props.ts
  src/components/navigation/Breadcrumbs/BreadcrumbMenuLink/stories/BreadcrumbMenuLink.stories.tsx
  src/components/navigation/Breadcrumbs/props.ts
Labels: minor

#584 `<BreadcrumbMenuLink />:` refactor to use new color and spacing tokens
  src/components/navigation/Breadcrumbs/BreadcrumbMenu/styles.ts
  src/components/navigation/Breadcrumbs/BreadcrumbMenuLink/stories/BreadcrumbMenuLink.stories.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbMenuLink/styles.ts
  src/components/navigation/Breadcrumbs/index.tsx
  src/components/navigation/Breadcrumbs/styles.ts
Labels: minor

#586 `<Breadcrumbs />:` create default and themed stories
  src/components/navigation/Breadcrumbs/BreadcrumbLink/index.tsx
  src/components/navigation/Breadcrumbs/BreadcrumbLink/props.ts
  src/components/navigation/Breadcrumbs/index.tsx
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.Desktop.stories.tsx
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.Mobile.stories.tsx
  src/components/navigation/Breadcrumbs/stories/Breadcrumbs.stories.tsx
  src/components/navigation/Breadcrumbs/styles.ts
Labels: minor

#588 `<Table />:` Refactor `<Pagination />` and Update Stories in `<Table />` Component
  src/components/data/Table/Pagination/index.tsx
  src/components/data/Table/Pagination/stories/Pagination.stories.tsx
  src/components/data/Table/Pagination/stories/PaginationController.tsx
  src/components/data/Table/Pagination/styles.ts
  src/components/data/Table/stories/Pagination.stories.tsx
Labels: minor

#572 Refactor so StyledNav isn’t a `flex` container in `<Nav />`
  src/components/navigation/Nav/styles.ts
Labels: minor

#592 `Refactor:` Update and Remove Props in `<Grid />` Component
  src/components/layouts/Grid/index.tsx
  src/components/layouts/Grid/props.ts
  src/components/layouts/Grid/stories/Grid.stories.tsx
  src/components/layouts/Grid/styles.ts
Labels: minor

#591 `<Table />:` define only the interface for `Table` not for `TableUI`
  src/components/data/Table/index.tsx
  src/components/data/Table/interface.tsx
  src/components/data/Table/props.ts
  src/components/data/Table/stories/Table.Paginations.stories.tsx
  src/components/data/Table/stories/Table.stories.tsx
Labels: minor

#576 Implement accordion is more than 2 sections in `<FullscreenNav />`
  src/components/navigation/FullscreenNav/index.tsx
  src/components/navigation/FullscreenNav/stories/FullscreenNav.MultiSections.stories.tsx
  src/components/navigation/FullscreenNav/styles.ts
  src/components/navigation/NavLink/index.tsx
Labels: minor

#597 Split onStepChange in two in `<Assisted />`
  src/components/feedback/Assisted/index.tsx
  src/components/feedback/Assisted/props.ts
  src/components/feedback/Assisted/stories/Assisted.Controller.tsx
Labels: minor

#600 Selete size prop refactor responsive in `<Assisted />`
  src/components/feedback/Assisted/index.tsx
  src/components/feedback/Assisted/props.ts
  src/components/feedback/Assisted/stories/Assisted.stories.tsx
  src/components/feedback/Assisted/styles.ts
Labels: minor

#595 Move the dependent interfaces to index.tsx in `<Table/>`
  src/components/data/Table/DisplayActions/index.tsx
  src/components/data/Table/index.tsx
  src/components/data/Table/interface.tsx
Labels: minor

#601 Delete sequential prop in `<Assisted />`
  src/components/feedback/Assisted/index.tsx
  src/components/feedback/Assisted/stories/Assisted.Controller.tsx
Labels: minor

#603 All the steps are divided equally `<Assisted />`
  src/components/feedback/Assisted/styles.ts
Labels: minor

#605 `<Tag />:` develop component
  src/components/data/Tag/Tag.stories.tsx
  src/components/data/Tag/index.tsx
  src/components/data/Tag/props.ts
  src/components/data/Tag/styles.ts
Labels: minor

#598 `<Header />:` Extend component to render links
  src/components/navigation/Header/index.tsx
  src/components/navigation/Header/props.ts
  src/components/navigation/Header/stories/Header.stories.tsx
  src/components/navigation/Header/styles.ts
  src/components/navigation/Tabs/stories/Tabs.stories.tsx
Labels: minor

#607 `<Button />:` appearance in disabled state depending on variant
  src/components/inputs/Button/index.tsx
  src/components/inputs/Button/styles.ts
Labels: minor

#599 `<SectionMessage />:` develop component
  src/components/feedback/SectionMessage/SectionMessage.stories.tsx
  src/components/feedback/SectionMessage/index.tsx
  src/components/feedback/SectionMessage/props.ts
  src/components/feedback/SectionMessage/styles.ts
Labels: minor

#602 Use Grid component in layout `<Assisted />`
  src/components/feedback/Assisted/index.tsx
  src/components/feedback/Assisted/styles.ts
Labels: minor

#608 Refactor appearance of Prev `<Button />` in `<Assisted />`
  src/components/feedback/Assisted/index.tsx
  src/components/feedback/Assisted/stories/Assisted.stories.tsx
Labels: minor

#609 fix: added missing components to exportation file index.ts
  src/index.ts
Labels: bug

#610 release desing system 5.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#611 Fix: Resolve Resource Distribution Incidents in Library
  src/index.ts
Labels: bug

#612 design-system new version 5.8.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#613 Adjust the link props as this should be optional in `<Header />`.
  src/components/data/Text/styles.ts
  src/components/navigation/Header/index.tsx
Labels: minor

#614 Release: design-system new version 5.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#617 Replace `<StyledContainerLabel />` by `<Stack />` into `<Select />`
  src/components/inputs/Select/interface.tsx
  src/components/inputs/Select/styles.ts
Labels: bug

#618 `Enhancement:` Improve `textAlign` Prop Typing in `<Text />` Component
  src/components/data/Text/props.ts
Labels: bug
