Repository selsa-inube/design-system, pull requests merged in 2023-11, with the labels that each got.

#619 update the colour palette of Presente
  src/shared/themes/presente/color/palette/palette.ts
Labels: bug

#626 `Fix`: Correct `<Nav/>` Marker Positioning to Align with Figma Standards
  src/components/navigation/Nav/index.tsx
Labels: minor

#625 Correct errors in the backward and forward steps in `<Assisted />`
  src/components/feedback/Assisted/index.tsx
Labels: minor

#628 `Adjustment:` Reposition `<OptionList/>` for Enhanced Design Consistency
  src/components/inputs/Select/OptionList/styled.ts
Labels: minor

#631 Release: new version 5.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
